FROM node:24.9.0 AS builder

ARG VITE_API_HOST
ARG VITE_SUPABASE_PROJECT_ID
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_URL

ENV VITE_API_HOST=$VITE_API_HOST
ENV VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID
ENV VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL

COPY package*.json ./
RUN npm install
COPY . .
RUN npx vite build

FROM nginx:1.29.1

COPY --from=builder dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
